### PR TITLE
feat#2 User 모델 설계

### LINKED ISSUE #3: [feat#2] User - 모델 설계 (User Model)
일반 회원용 계정 1개, 운영진용 계정 1개를 만들어 사용할 계획이다.

email, password, level 필드로 구성한다.

### PR DESCRIPTION
**Pull request by hoon4233**
email - EmailField
password - CharField
level - CharField

close #3

### CODE REVIEW

**Review by hoon4233 — COMMENTED** [review]
Ok

**Review by Sonjeongbeom — APPROVED** [review]
feat#2 review completed

**Review by Sonjeongbeom — COMMENTED** [review]
#3 review completed

**Review by Sonjeongbeom — COMMENTED** [review]
feat#3 review completed

**Pull request merged**
